"""Teste automático de importação

Revision ID: 797b963a499c
Revises: 0552cfd4a976
Create Date: 2025-02-09 22:12:14.089162

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '797b963a499c'
down_revision: str | None = '0552cfd4a976'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
