"""Fix primary key auto-increment issue

Revision ID: ddd724a9da89
Revises: 103a0a76f12b
Create Date: 2025-02-03 23:42:53.882296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd724a9da89'
down_revision: Union[str, None] = '103a0a76f12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
